#Program to guess the number
import random  
print("I am thinking of a number between 1 and 10.")   
x=int(input("What is the number?"))  #prompting user to enter number
print("The number was:",random.randint(1,10))  #number generated by random function
print("You guessed:",x)  #users guess